development:
  adapter: postgresql
  encoding: utf8
  database: Sicueft_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: Sicueft_test
  pool: 5
  username: 
  password:


cucumber:
  <<: *TEST